LP3Service:
  WalletId:
    settings-key: LP3-WalletId
  
  Db:
    LogsConnString:
      settings-key: LP3-LogsConnString
      types:
        - AzureTableStorage

    DataConnectionString:
      settings-key: LP3-DataConnectionString
      types:
        - AzureTableStorage
        
  Rabbit:
    Subscribers:
      LykkeOrders:
        ConnectionString:
          settings-key: LP3-Rabbit-Subscribers-LykkeOrders-ConnectionString
          types:
          - RabbitMq
        ExchangeName:
          settings-key: LP3-Rabbit-Subscribers-LykkeOrders-Exchange

      LykkeOrderBooks:
        ConnectionString:
          settings-key: LP3-Rabbit-Subscribers-LykkeOrderBooks-ConnectionString
          types:
          - RabbitMq
        ExchangeName:
          settings-key: LP3-Rabbit-Subscribers-LykkeOrderBooks-Exchange
          
  ExternalExchanges:
    settings-key: LP3-ExternalExchanges
    types:
      - JsonArray
      
  OrdersCreationPeriod:
    settings-key: LP3-OrdersCreationPeriod
    types:
      - Optional

  Timers:
    BalanceTimer:
      settings-key: LP3-Timers-BalanceTimer

  AssetMappings:
    settings-key: LP3-AssetMappings
    types:
      - JsonArray

MatchingEngineClient:
  IpEndpoint:
    Port:
      settings-key: MatchingEngine-Port
    Host:
      settings-key: MatchingEngine-Host

AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl

BalancesServiceClient:
  ServiceUrl:
    settings-key: BalancesServiceUrl

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
      settings-key: MonitoringServiceUrl

